### ISSUE TITLE
Cannot use an externally hosted Token Frame

### ISSUE THREAD

**Issue by rikmarais** [fryguy1013/pdftofoundry#11]
This is a follow-up to https://github.com/fryguy1013/pdftofoundry/issues/10, where an image hosted on the Forge Asset Library was used as a Token Frame for a PDF to Foundry import.

It looks like Token Frame does not work for absolute URLs pointing to externally hosted images.
This holds true for when you do a PDF Import on locally hosted Foundry when using [Foundry's S3 integration](https://foundryvtt.com/article/aws-s3/) and pointing the Token Frame image to an S3 hosted path.

![image](https://github.com/fryguy1013/pdftofoundry/assets/34374883/2f6f74f6-94ce-46d8-9c2f-adb6c421619f)

![image](https://github.com/fryguy1013/pdftofoundry/assets/34374883/91f4e03c-e164-4314-9d80-392244c6848f)

Because the Forge Assets Library is hosted external to the world itself, it runs into the same issue.
It is possible to use a relative path which the Forge server will proxy to the Assets Library. This runs into the same issue, leading me to believe that the problem doesn't come from interpreting the absolute path, but rather the canvas is considered ['tainted' by cross-origin data](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) because the supplied Token Frame is hosted externally.

As mentioned earlier in this issue, this holds true for any externally hosted Token Frame images, including using the standard S3 integration to get absolute URL to the Token Frame.

For any Forge user encountering this issue, I would recommend doing the PDF to Foundry import locally, and then uploading the `pdftofoundry` folder in your `FoundryVTT/Data` folder, and then the world, to Forge via the Import Wizard.

**Comment by fryguy1013** [comment]
Possibly fixed in 5.0.0. I added CORS settings to the image loading but it's up to the hosting provider to have the correct CORS headers. It's just web security and not much I can do beyond that 🤷
