### ISSUE TITLE
Mod asking me to update to a system version (5.10.0) that doesn't seem to exist?

### ISSUE THREAD

**Issue by rjakeFoundry** [fryguy1013/pdftofoundry#12]
Pf2e 5.3.2
PDF to Foundry is the only mod active.

When I click PDF Importer I get this message, but I believe 5.3.2 is the most recent version of the pf2e system.
"You need to be using a version of the pf2e system at least 5.10.0. You are only using version 5.3.2!"

![image](https://github.com/fryguy1013/pdftofoundry/assets/158752510/26bf015b-7850-488f-91f8-334022f1d0f4)

**Comment by fryguy1013** [comment]
PF2e system is up to 5.13.2.

https://foundryvtt.com/packages/pf2e/
