### ISSUE TITLE
Age of Ashes - Hellnight Hill - handouts not working

### ISSUE THREAD

**Issue by ksignorini** [fryguy1013/pdftofoundry#14]
Age of Ashes Hellknight Hill Handouts do not import correctly.

<img width="977" alt="image" src="https://github.com/fryguy1013/pdftofoundry/assets/6867660/d2ca7983-da62-480e-9743-a4aaa6f7e6dd">

**Comment by esterlinej** [comment]
This affects all modules, many of the `.webp` image files are included but appear corrupted.

![image](https://github.com/fryguy1013/pdftofoundry/assets/231105/67b60b6b-9bbf-4667-a240-1a19082e90c6)

**Comment by LumberKing** [comment]
> Age of Ashes Hellknight Hill Handouts do not import correctly.
> 
> <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/6867660/304816754-d2ca7983-da62-480e-9743-a4aaa6f7e6dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTUwNDAsIm5iZiI6MTcxMzYxNDc0MCwicGF0aCI6Ii82ODY3NjYwLzMwNDgxNjc1NC1kMmNhNzk4My1kYTYyLTQ4MGUtOTc0My1hNGFhYTZmN2U2ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTIwNTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNlMTMxZWUzYzQ5YWYzNjRjMmRhZTA2YTM5N2FiZGJkYjEyYTYzZDE2NGE0NWYzMDIxOWRmYzFjNmNiZDFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tYbJazdfizvIareDSZLLi_rTX4dlPxthb4h9U6-ErBU">



> This affects all modules, many of the `.webp` image files are included but appear corrupted.
> 
> ![image](https://private-user-images.githubusercontent.com/231105/322147617-67b60b6b-9bbf-4667-a240-1a19082e90c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTUwMzksIm5iZiI6MTcxMzYxNDczOSwicGF0aCI6Ii8yMzExMDUvMzIyMTQ3NjE3LTY3YjYwYjZiLTliYmYtNDY2Ny1hMjQwLTFhMTkwODJlOTBjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMjA1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDhjMWM4ZDVlOTI0NDVmYzU3MTRiZDNkZjE5MDFiODdlMDI3Njg2MDhlYTIyNDA2YjRiYmVlMzczMjRkZTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MajXuAmUXoccrSxJyzgV-7kHsxl_w1Sm0ng0wocO5GM)

Yeah, seeing this issue on Agents of Edgewatch and Strength of Thousands APs.

**Comment by overkongen** [comment]
I had the same problem. A workaround is to install Foundry v10.291, PF2e 4.12.9 and PDF to Foundry 4.0.0 and the pictures of the handouts will import properly.

**Comment by scooper4711** [comment]
So I'd have to keep an instance of v10 foundry around, import modules, then upgrade to v11 or v12 for each module I want to mess with?

**Comment by fryguy1013** [comment]
Fixed in 5.0.0
