### ISSUE TITLE
Unable to import Paizo product

### ISSUE THREAD

**Issue by SDShannonS** [fryguy1013/pdftofoundry#15]
I purchased a PDF of the 2E adventure, Crown of the Kobold King. I attempted to import it as I have successfully imported other such adventures, but consistently receive the error message, "failed to detect pdf. cannot proceed :("

Issue persists with both the SingleFile PDF and the OneFilePerChapter PDFs for these adventures.

I have verified that they contain the Paizo watermark with my info and a purchase date of today.

**Comment by SDShannonS** [comment]
I see that you've closed the issue with no comment - does that mean you don't know why it's doing it but you're not going to spend the time to figure it out?

**Comment by LumberKing** [comment]
> I see that you've closed the issue with no comment - does that mean you don't know why it's doing it but you're not going to spend the time to figure it out?

There was an announcement made three years ago that he would no longer be adding any new contents (the final one being Quest for the Frozen Flame Adventure Path).

[https://www.reddit.com/r/Pathfinder2e/comments/tuz3ip/pdftofoundry_module_no_more_new_aps_being_added/](https://www.reddit.com/r/Pathfinder2e/comments/tuz3ip/pdftofoundry_module_no_more_new_aps_being_added/)
