### ISSUE TITLE
Some Edgewatch (Book 1) Handouts Not Importing Correctly

### ISSUE THREAD

**Issue by nick-mckenna** [fryguy1013/pdftofoundry#16]
- Foundry v11 Build 315 running on The Forge.
- PF2e Module v5.15.0

I am importing the official Paizo English PDF of Agents Of Edgewatch Part 1 Devil At The Dreaming Palace .

There were no error messages during the import, but afterwards, some of the handouts are broken. I've attached a PNG showing how it looks in the Journal.

![edgewatch](https://github.com/fryguy1013/pdftofoundry/assets/50596528/7cb4eb93-1fd5-4e6c-bef9-0e8fd8dbd0dd)

**Comment by LumberKing** [comment]
> * Foundry v11 Build 315 running on The Forge.
> * PF2e Module v5.15.0
> 
> I am importing the official Paizo English PDF of Agents Of Edgewatch Part 1 Devil At The Dreaming Palace .
> 
> There were no error messages during the import, but afterwards, some of the handouts are broken. I've attached a PNG showing how it looks in the Journal.
> 
> ![edgewatch](https://private-user-images.githubusercontent.com/50596528/321662611-7cb4eb93-1fd5-4e6c-bef9-0e8fd8dbd0dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTQ5NTUsIm5iZiI6MTcxMzYxNDY1NSwicGF0aCI6Ii81MDU5NjUyOC8zMjE2NjI2MTEtN2NiNGViOTMtMWZkNS00ZTZjLWJlZjktMGU4ZmQ4ZGJkMGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmRkN2YxODQ4Mjk5MTk0MWVlZTU5NmU4ZGE2Zjg2MDMwYTY2ZDlkODBiZGExMTVjYjNjZTkyYzdlNTk4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EbiuboLLpAakehRNkPJDqh6ETPUHdS8eyFoOZG_1hj8)

Having the same issue with Book 6.

**Comment by fryguy1013** [comment]
Fixed in 5.0.0

**Comment by nick-mckenna** [comment]
Thanks! This change is a big step towards my group getting started on Edgewatch!
