### ISSUE TITLE
Not showing in Gameworld

### ISSUE THREAD

**Issue by 5olu5pul5** [fryguy1013/pdftofoundry#22]
So I have an issue. The pdf-importer isn´t showing in the modul administration panel. I already updated all files and I doubt to have compatibility issues since there are just about 7 modules installed. 
Please ignore the Statblock Importer, I just downloaded it after I found out your module isn´t working rn.
Sorry to give you this extra work, I appreciate what you´ve done so far and hope my german rudeness isn´t showing!

![grafik](https://github.com/user-attachments/assets/6abb7123-940b-49cf-b363-054d565472f8)
![grafik](https://github.com/user-attachments/assets/b2172460-5572-4fad-8a0c-955aa6ad1e8f)

**Comment by fryguy1013** [comment]
This module only works in the pathfinder 2e system, and only supports Paizo watermarked PDFs.
