### ISSUE TITLE
Suggestion: Check for the official Pathfinder Tokens: Bestiary module when importing adventures

### ISSUE THREAD

**Issue by TheL0rd0fSpace** [fryguy1013/pdftofoundry#28]
While it's very handy that you have support for importing the official Bestiaries/NPC Gallery and using those art assets when generating tokens, it has the two downsides that:

1) If that token exists in the PF Tokens: Bestiary module, that module usually looks better (since its properly centered and such, compare the Zombie Shamblers), and
2) If that npc/monster exists in the Bestiary books, but doesn't have an art asset, then it will only have the default blank asset (see the Plague Zombie for example).

If, when creating new npc actors, the module not only checked its bestiary/gmg folders, but also checked for the Bestiary module for art assets to use, it would make this all the better.

Cheers!

**Comment by fryguy1013** [comment]
It just uses the built-in foundry art replacement. You can configure that to prioritize them.
