### ISSUE TITLE
Import fails to create mapping entries in generated files

### ISSUE THREAD

**Issue by roxim5** [fryguy1013/pdftofoundry#4]
PDF to Foundry Version: 4.1.1
PF2e Version: 5.2.3
Foundry Version: 11.306

Fresh world, no other modules enabled, no previous pdftofoundry folders or files in Data. 

Import Bestiary 1, image extraction happens without issues. /pdftofoundry/<book> folder gets created and images populate as expected. Once that completes, the mapping files are generated. However, the mapping files are empty and contain no information to map the images to the bestiary actors. Attached them here.

No errors occur during import or at any time. 
This behavior occurs whether or not I toggle the options:
- Always use imported icons
- Use actor/token images

[pdftofoundry-files.zip](https://github.com/fryguy1013/pdftofoundry/files/12196061/pdftofoundry-files.zip)

**Comment by roxim5** [comment]
Looks like art path assignment works on actors that get imported in an adventure, but it doesn't add anything to the mapping file still.

**Comment by jadon83** [comment]
having the same issue here today, the importer wont generate the mapping files for the bestiary 1 or 2 pdf's

**Comment by zachjb** [comment]
Same issue here. Also tried the Gamemastery Guide and that failed in the same way.

PDF to Foundry Version: 4.1.1
PF2e Version: 5.4.2
Foundry Version: 11.308

All versions latest as of 09/02/2023.

**Comment by fryguy1013** [comment]
Fixed in 4.1.2
