### ISSUE TITLE
PDF to Foundry Module v11

### ISSUE THREAD

**Issue by UnlivingLuke** [fryguy1013/pdftofoundry#7]
Is PDF to Foundry importer module working at the moment? I'm using version 11 and have the module updated to latest. However, when I attempt to import an official Paizo PDF file...nothing happens (unlike before, it would import with no issues creating scenes, journals, etc.)

**Comment by jadon83** [comment]
I had the same issue, i tried disabling all modules except pdf to foundry importer and then it worked, temporary fix i suppose

**Comment by fryguy1013** [comment]
Duplicate of #3
